# Generated by Django 6.0.3 on 2026-04-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_posts',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
